### ISSUE TITLE
bash: det: command not found

### ISSUE THREAD

**Issue by lions2** [alertot/detectem#11]
* detectem version: 0.6.1
* Python version: 3.5.3
* Operating System: Debian GNU/Linux 9.3 (stretch) x86_64

### Description
Something inherently missing from $PATH ?

### What I Did
1) Installed Docker and ran 'docker pull scrapinghub/splash'
2) ran 'pip3 install detectem'
3) ran 'det http://example.webscraping.com' , received command not found
4) attempted to add 'PATH="$HOME/.local/bin:$PATH"' to my ~/.profile , followed by 'source ~/.profile'
5) Still did not work, removed that code as I clearly do not understand the issue.

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```
$pip3 show detectem

Name: detectem
Version: 0.6.1
Summary: Detect software in websites.
Home-page: https://github.com/spectresearch/detectem
Author: Claudio Salazar
Author-email: csalazar@spect.cl
License: MIT
Location: /home/notions/.local/lib/python3.5/site-packages
Requires: parsel, click, docker, requests, zope.interface

**Comment by csalazar** [comment]
Hi @lions2, thanks for the report. Where does `pip3` installs `det` executable? If `det` is not present in `$HOME/.local/bin`, setting `PATH` won't work anyway.

**Comment by csalazar** [comment]
We've dropped support for Python < 3.6.
