### ISSUE TITLE
unable to install

### ISSUE THREAD

**Issue by guhailong18** [alertot/detectem#17]
ERROR: Could not find a version that satisfies the requirement pypiwin32==220; sys_platform == "win32" and python_version >= "3.6" (from docker==3.4.1->detectem) (from versions: 219, 223)
ERROR: No matching distribution found for pypiwin32==220; sys_platform == "win32" and python_version >= "3.6" (from docker==3.4.1->detectem)

(i use pip and docker,also have this problen)

**Comment by chrisdlangton** [comment]
I also couldn't install, but eventually i figured it out. 

Try;

server no. 1 (or PC/laptop)

```
docker create --name splash -p "8050:8050" --restart unless-stopped scrapinghub/splash
docker start splash
```

This works: http://<server 1 ip>:8050

on any Server/PC/Laptop terminal ;

```
python3 -m pip -q install --user -U detectem==0.7.0
SETUP_SPLASH=False SPLASH_URL=http://<server 1 ip>:8050 det --debug --metadata --format json https://www1.example.com    
```

It works

**Comment by csalazar** [comment]
Sorry @guhailong18, I can't support this project under Windows because I don't use Windows.

**Comment by guhailong18** [comment]
ok. Thank you for your reply. 13430138475 邮箱：13430138475@139.com 签名由 网易邮箱大师 定制 On 12/01/2019 18:34, Claudio Salazar wrote: Sorry @guhailong18, I can't support this project under Windows because I don't use Windows. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.
