### ISSUE TITLE
Syntax errors for python 3.7.4

### ISSUE THREAD

**Issue by chrisdlangton** [alertot/detectem#19]
* detectem version: all
* Python version: 3.7.4
* Operating System: amazonlinux2

```
File "/usr/local/lib/python3.7/site-packages/detectem/settings.py", line 25, in <module>
SPLASH_MAX_TIMEOUT = int(os.environ.get('SPLASH_MAX_TIMEOUT', '120'))
ValueError: invalid literal for int() with base 10: ''
```

**Comment by csalazar** [comment]
Hi @chrisdlangton , you need to set the environment variable to a valid integer value, from the output I think that you've put `SPLASH_MAX_TIMEOUT=""`. Is that the case?
