### ISSUE TITLE
det module don't work

### ISSUE THREAD

**Issue by zengraoli** [alertot/detectem#26]
hello friend. 

i run det https://www.baidu.com

tips:'Could not connect to Docker daemon. Please ensure Docker is running.'

but i sure that docker is running.

`
root@zeng:/var/lib# service docker status
docker start/running, process 4232
`

docker and images info:
`
root@zeng:/var/lib# docker -v

Docker version 1.6.2, build 7c8fca2

root@zeng:/var/lib# docker images

REPOSITORY           TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
scrapinghub/splash   latest              1f7658a4cabf        10 weeks ago        2.172 GB

`

**Comment by csalazar** [comment]
Hi, the user running detectem has access to docker socket? If not, try with `sudo`.
